[package]
name = "mezura"
version = "1.1.0"
authors = ["subamanis <petrospapa21@gmail.com>"]
edition = "2024"
default-run = "mezura"

[[bin]]
name = "mezura"
path = "src/main.rs"

[profile.release]
debug = true

[dependencies]
colored = "2"
memchr = "2"
chrono = "0.4.19"
crossbeam-deque = "0.8"
num_cpus = "1.13.0"
directories = "4.0.1"
include_dir = "0.6.2"
