Language
Dockerfile

Extensions
dockerfile

Filenames
Dockerfile Containerfile

String symbols
" '

Escape character
\

Comment symbols
#

Keyword
    NAME
    stages
    ALIASES
    FROM
Keyword
    NAME
    commands
    ALIASES
    RUN
